server:
  port: 8000

spring:
  profiles:
    active: dev
  application:
    name: demo-client

feign:
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
